SELECT kl.LoanId,
va.BuildingType,
va.PropertyOccupancyType,
va.LoanProcedure,
va.MilitaryBranchOfService,
va.VeteranServiceType,
va.PurposeOfLoan,
va.TypeOfOwnsership,
va.LoanCode,
va.TypeOfMortgage,
va.AppraisalType,
va.ManufacturedHome,
va.TypeOfStructure,
va.PropertyDesignation,
va.FundingFeeExempt,
va.AnnualRealEstateTaxes,
va.LotDimensions,
va.IrregularLotSizeInSquareFeet,
va.InsuranceType,
va.ApplicantBirthDate,
va.VeteranDischargedIndicator,
va.VAClaimNumber,
va.MailingAddress,
va.MailingCity,
va.MailingState,
va.MailingPostalCode,
va.VaLoanSummaryApplicantType,
va.ApplicantFirstNameWithMiddleName,
va.ApplicantLastNameWithSuffix,
va.ApplicantTaxIdentificationIdentifier,
va.ApplicantHomePhoneNumber,
va.ApplicantAddressStreetLine1,
va.ApplicantAddressCity,
va.ApplicantAddressState,
va.ApplicantAddressPostalCode,
va.ApplicantEmailAddressText,
va.PreviousVALoanIndicator,
va.PurpleHeartRecipientIndicator,
va.PreDischargeClaimPending,
va.WillUseCertificateFor,
va.LoanAnalysisRemarks1,
va.LoanAnalysisRemarks2,
va.LoanAnalysisRemarks3,
va.LoanAnalysisRemarks4,
va.LoanAnalysisRemarks5,
va.LoanAnalysisRemarks6,
va.LoanAnalysisRemarks7,
va.LoanAnalysisRemarks8,
va.LoanAnalysisRemarks9,
va.PayoffIndicator1,
va.PayoffIndicator2,
va.PayoffIndicator3,
va.PayoffIndicator4,
va.PayoffIndicator5,
va.PayoffIndicator6,
va.PayoffIndicator7,
va.PayoffIndicator8,
va.PayoffIndicator9,
va.TotalDebtMonthlyPayment,
va.UnderwriterRecommendation,
va.UnderwriterRecommendationDate,
va.FinalAction,
va.FinalActionDate,
va.FinalFundingFeeAmount,
va.TotalForMaxLoanAmount,
va.InitialTotal,
va.PreliminaryDiscountAmount,
va.OriginationFeeAmount,
va.PreliminaryFundingFeeAmount,
va.OtherClosingCosts,
va.PreliminaryTotal,
va.FinalDiscountAmount,
va.DiscountPercentage,
va.TotalRooms,
va.TotalBaths,
va.TotalBedrooms,
va.OriginalValueEstimateChanged,
va.PaidInFullVALoanNumber,
va.OriginalLoanAmount,
va.OriginalInterestRate,
va.SystemUsed,
va.OriginalTerm,
va.VAOriginalMonthlyPayment,
va.VAOriginalAmortizationType,
va.VARecoupmentMonthlyDecreaseInPayment,
va.VARecoupmentTotalClosingCosts,
va.VARecoupmentClosingCosts,
va.VARecoupmentYears,
va.VARecoupmentMonths,
va.VALatePaymentIn6Months,
va.EntitlementCode,
va.RiskClasification,
va.CreditScore,
va.TypeOfHybridARM,
va.ApplicantHmdaGenderType,
va.LoanProcessedUnderAU,
va.PropertyGrossLivingArea,
va.AgeOfProperty,
va.DateSAR,
va.CurrentlyOnMilitaryDuty,
va.VABenefitRelatedIndebtedness,
va.ClaimDisabilityBenefits,
va.TypeOfVeteran,
va.PriorLoanType,
va.AutomaticProcedure,
va.PriorApprovalProcedure,
va.AmountTypeWithheld,
va.AmountWithheld,
va.DisabilityAmountCollected,
va.VATrackingSARName,
va.VATrackingIsSARLAPPCertified,
va.VAAppraisalSentDate,
va.VANOVDateReceived,
va.VANOVDateReviewed,
va.VANOVIssuedDate,
va.VADateNOVAppraisalMailedToBorrower,
va.VATrackingOrderedDate,
va.VATrackingCOEIssueDate,
va.VATrackingPaidDate,
va.VATrackingReceiptReceived,
va.VATrackingLoanGuaranteeCertReceipt,
va.VATrackingGSAExclusionaryListChecked,
va.VATrackingCertOfCommitmentIssued,
va.VATrackingInuranceFloodPolicy,
va.VATrackingInuranceHazardPolicy,
va.VATrackingInuranceWoodDestroyingPolicy,
va.VATrackingInuranceWindOrHailPolicy,
va.VAQualificationCountryRegion,
va.VAQualificationCountyLimits,
va.TotalMonthlyPayment,
va.TotalProposedMonthlyPayment,
va.ExistingVALoanNumber,
va.ExistingLoanBalance,
va.EstimatedImpactofLoanBalanceAmount,
va.EstimatedImpactofRemainingTermMonths,
va.EstimatedImpactofInterestRate,
va.ExistingTotalRemainingPaymentAmount,
va.ProposedTotalRemainingPaymentAmount,
va.EstimatedImpactofTotalRemainingPaymentAmount,
va.EstimatedImpactofLTV,
va.ExistingReasonableAppraisedValue,
va.ExistingHomeEquityRemainingAmount,
va.ProposedHomeEquityRemainingAmount,
va.EstimatedImpactofHomeEquityRemainingAmount,
va.CashDisbursedToBorrowerAmount,
va.DisbursementsLessPayoffAmount,
va.VAImpactLoanBalanceIndicator,
va.VAImpactRemainingTermIndicator,
va.VAImpactInterestRateIndicator,
va.VAImpactScheduledPaymentsIndicator,
va.VAImpactLTVIndicator,
va.VAImpactRemainingEquityIndicator,
va.TotalPaidOverLifeIncreasedAmount,
va.ExistingLoanFirstPaymentDate,
va.TotalClosingCostLessGuaranteeFee,
va.VACashOutRefinanceType,
va.AmountOfProposedLiens,
va.CdNonShoppableLessFundingFee,
va.LeTotalClosingCosts,
va.LeRecoupmentMonths,
va.IncludeSectionAIndicator,
va.IncludeSectionBVaFundingFeeIndicator,
va.IncludeSectionBOtherIndicator,
va.IncludeSectionCIndicator,
va.IncludeSectionEIndicator,
va.IncludeSectionFIndicator,
va.IncludeSectionGIndicator,
va.IncludeSectionHIndicator,
va.IncludeLenderCreditIndicator,
va.RefinancePropertyExistingLienAmount,
va.RefinancedModified,
va.EscrowItemsToComplete,
va.UnderwriterVaIdNumber,
va.VaPurposeOfLoan,
va.ApplicantAddressStreetLine2,
va.SellerOwnerPhone,
va.SellerOwnerEmail,
va.Id,
va.IsDelinquent30Days,
va.ModifiedUtc,
va.VaLoanDataId


INTO dbo.LoanVaData
FROM Loan kl 
JOIN [WIN-T0FCRL091AK].Encompass.elliedb.Loan l ON kl.Loannum = l.Loannumber 
LEFT JOIN [WIN-T0FCRL091AK].Encompass.elliedb.VALoanData va ON va.encompassid = l.encompassid 

--DROP TABLE dbo.LoanVaData

--ALTER TABLE dbo.LoanVaData
--ALTER COLUMN VALoanDataId NVARCHAR(100) NOT NULL;

--ALTER TABLE dbo.LoanVaData
--ADD CONSTRAINT PK_LoanVaData_LoanVaDataId PRIMARY KEY (VALoanDataId);

--ALTER TABLE dbo.LoanVaData
--DROP CONSTRAINT [FK_LoanVaData(LoanID)_Loan(LoanID)];

--ALTER TABLE dbo.LoanVaData
--ADD CONSTRAINT [FK_LoanVaData(LoanID)_Loan(LoanID)]
--FOREIGN KEY (LoanID)
--REFERENCES dbo.Loan(LoanID)
--ON DELETE CASCADE;

SELECT * FROM VALoanData